from openpydss.opendss.model.dssobject import DSSObject


class Storage(DSSObject):
    def __init__(
            self,
            phases="3",
            bus1="storage_1",
            kv="12.47",
            conn="wye",
            kW="0",
            kvar="0",
            pf="1",
            kVA="25",
            pct_Cutin="0",
            pct_Cutout="0",
            EffCurve="",
            VarFollowInverter="No",
            kvarMax="25",
            kvarMaxAbs="25",
            WattPriority="NO",
            PFPriority="NO",
            pct_PminNoVars="-1",
            pct_PminkvarMax="-1",
            kWrated="25",
            pct_kWrated="100",
            kWhrated="50",
            kWhstored="50",
            pct_stored="100",
            pct_reserve="20",
            State="IDLING",
            pct_Discharge="100",
            pct_Charge="100",
            pct_EffCharge="90",
            pct_EffDischarge="90",
            pct_IdlingkW="1",
            pct_Idlingkvar="",
            pct_R="0",
            pct_X="50",
            model="1",
            Vminpu="0.9",
            Vmaxpu="1.1",
            Balanced="No",
            LimitCurrent="No",
            yearly="",
            daily="",
            duty="",
            DispMode="default",
            DischargeTrigger="0",
            ChargeTrigger="0",
            TimeChargeTrig="2",
            Class="1",
            DynaDLL="",
            DynaData="()",
            UserModel="",
            UserData="()",
            debugtrace="NO",
            spectrum="",
            basefreq="60",
            enabled="true",
            like="",
    ):
        super().__init__()
        self.phases = phases
        self.bus1 = bus1
        self.kv = kv
        self.conn = conn
        self.kW = kW
        self.kvar = kvar
        self.pf = pf
        self.kVA = kVA
        self.pct_Cutin = pct_Cutin
        self.pct_Cutout = pct_Cutout
        self.EffCurve = EffCurve
        self.VarFollowInverter = VarFollowInverter
        self.kvarMax = kvarMax
        self.kvarMaxAbs = kvarMaxAbs
        self.WattPriority = WattPriority
        self.PFPriority = PFPriority
        self.pct_PminNoVars = pct_PminNoVars
        self.pct_PminkvarMax = pct_PminkvarMax
        self.kWrated = kWrated
        self.pct_kWrated = pct_kWrated
        self.kWhrated = kWhrated
        self.kWhstored = kWhstored
        self.pct_stored = pct_stored
        self.pct_reserve = pct_reserve
        self.State = State
        self.pct_Discharge = pct_Discharge
        self.pct_Charge = pct_Charge
        self.pct_EffCharge = pct_EffCharge
        self.pct_EffDischarge = pct_EffDischarge
        self.pct_IdlingkW = pct_IdlingkW
        self.pct_Idlingkvar = pct_Idlingkvar
        self.pct_R = pct_R
        self.pct_X = pct_X
        self.model = model
        self.Vminpu = Vminpu
        self.Vmaxpu = Vmaxpu
        self.Balanced = Balanced
        self.LimitCurrent = LimitCurrent
        self.yearly = yearly
        self.daily = daily
        self.duty = duty
        self.DispMode = DispMode
        self.DischargeTrigger = DischargeTrigger
        self.ChargeTrigger = ChargeTrigger
        self.TimeChargeTrig = TimeChargeTrig
        self.Class = Class
        self.DynaDLL = DynaDLL
        self.DynaData = DynaData
        self.UserModel = UserModel
        self.UserData = UserData
        self.debugtrace = debugtrace
        self.spectrum = spectrum
        self.basefreq = basefreq
        self.enabled = enabled
        self.like = like
