from openpydss.opendss.model.dssobject import DSSObject


class Transformer(DSSObject):
    def __init__(
            self,
            phases="3",
            windings="2",
            wdg="1",
            bus="transformer_1",
            conn="wye ",
            kV="12.47",
            kVA="1000",
            tap="1",
            pct_R="0.2",
            Rneut="-1",
            Xneut="0",
            buses="[transformer_1, transformer_2, ]",
            conns="[wye, wye, ]",
            kVs="[12.47, 12.47, ]",
            kVAs="[1000, 1000, ]",
            taps="[1, 1, ]",
            XHL="7",
            XHT="35",
            XLT="30",
            Xscarray="[7, ]",
            thermal="2",
            n=".8",
            m=".8",
            flrise="65",
            hsrise="15",
            pct_loadloss="0.4",
            pct_noloadloss="0",
            normhkVA="1100",
            emerghkVA="1500",
            sub="n",
            MaxTap="1.1",
            MinTap="0.9",
            NumTaps="32",
            subname="",
            pct_imag="0",
            ppm_antifloat="1",
            pct_Rs="[0.2, 0.2, ]",
            bank="",
            XfmrCode="",
            XRConst="NO",
            X12="7",
            X13="35",
            X23="30",
            LeadLag="Lag",
            WdgCurrents="0, (0), 0, (0), 0, (0), 0, (0), 0, (0), 0, (0), ",
            Core="shell",
            RdcOhms="0.08811718",
            Seasons="1",
            Ratings="[1100,]",
            normamps="50.929",
            emergamps="69.449",
            faultrate="0.007",
            pctperm="100",
            repair="36",
            basefreq="60",
            enabled="true",
            like="",
    ):
        super().__init__()
        self.phases = phases
        self.windings = windings
        self.wdg = wdg
        self.bus = bus
        self.conn = conn
        self.kV = kV
        self.kVA = kVA
        self.tap = tap
        self.pct_R = pct_R
        self.Rneut = Rneut
        self.Xneut = Xneut
        self.buses = buses
        self.conns = conns
        self.kVs = kVs
        self.kVAs = kVAs
        self.taps = taps
        self.XHL = XHL
        self.XHT = XHT
        self.XLT = XLT
        self.Xscarray = Xscarray
        self.thermal = thermal
        self.n = n
        self.m = m
        self.flrise = flrise
        self.hsrise = hsrise
        self.pct_loadloss = pct_loadloss
        self.pct_noloadloss = pct_noloadloss
        self.normhkVA = normhkVA
        self.emerghkVA = emerghkVA
        self.sub = sub
        self.MaxTap = MaxTap
        self.MinTap = MinTap
        self.NumTaps = NumTaps
        self.subname = subname
        self.pct_imag = pct_imag
        self.ppm_antifloat = ppm_antifloat
        self.pct_Rs = pct_Rs
        self.bank = bank
        self.XfmrCode = XfmrCode
        self.XRConst = XRConst
        self.X12 = X12
        self.X13 = X13
        self.X23 = X23
        self.LeadLag = LeadLag
        self.WdgCurrents = WdgCurrents
        self.Core = Core
        self.RdcOhms = RdcOhms
        self.Seasons = Seasons
        self.Ratings = Ratings
        self.normamps = normamps
        self.emergamps = emergamps
        self.faultrate = faultrate
        self.pctperm = pctperm
        self.repair = repair
        self.basefreq = basefreq
        self.enabled = enabled
        self.like = like
