class Transformer:
    phases = "3"  # type: str
    windings = "2"  # type: str
    wdg = "1"  # type: str
    bus = "transformer_1"  # type: str
    conn = "wye "  # type: str
    kV = "12.47"  # type: str
    kVA = "1000"  # type: str
    tap = "1"  # type: str
    pct_R = "0.2"  # type: str
    Rneut = "-1"  # type: str
    Xneut = "0"  # type: str
    buses = "[transformer_1, transformer_2, ]"  # type: str
    conns = "[wye, wye, ]"  # type: str
    kVs = "[12.47, 12.47, ]"  # type: str
    kVAs = "[1000, 1000, ]"  # type: str
    taps = "[1, 1, ]"  # type: str
    XHL = "7"  # type: str
    XHT = "35"  # type: str
    XLT = "30"  # type: str
    Xscarray = "[7, ]"  # type: str
    thermal = "2"  # type: str
    n = ".8"  # type: str
    m = ".8"  # type: str
    flrise = "65"  # type: str
    hsrise = "15"  # type: str
    pct_loadloss = "0.4"  # type: str
    pct_noloadloss = "0"  # type: str
    normhkVA = "1100"  # type: str
    emerghkVA = "1500"  # type: str
    sub = "n"  # type: str
    MaxTap = "1.1"  # type: str
    MinTap = "0.9"  # type: str
    NumTaps = "32"  # type: str
    subname = ""  # type: str
    pct_imag = "0"  # type: str
    ppm_antifloat = "1"  # type: str
    pct_Rs = "[0.2, 0.2, ]"  # type: str
    bank = ""  # type: str
    XfmrCode = ""  # type: str
    XRConst = "NO"  # type: str
    X12 = "7"  # type: str
    X13 = "35"  # type: str
    X23 = "30"  # type: str
    LeadLag = "Lag"  # type: str
    WdgCurrents = "0, (0), 0, (0), 0, (0), 0, (0), 0, (0), 0, (0), "  # type: str
    Core = "shell"  # type: str
    RdcOhms = "0.08811718"  # type: str
    Seasons = "1"  # type: str
    Ratings = "[1100,]"  # type: str
    normamps = "50.929"  # type: str
    emergamps = "69.449"  # type: str
    faultrate = "0.007"  # type: str
    pctperm = "100"  # type: str
    repair = "36"  # type: str
    basefreq = "60"  # type: str
    enabled = "true"  # type: str
    like = ""  # type: str
